/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_manuelvalladares;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mevl1
 */
public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CREAR_USUARIO = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_pf_nombre = new javax.swing.JTextField();
        cb_pf_sexo = new javax.swing.JComboBox<>();
        tf_pf_usuario = new javax.swing.JTextField();
        tf_pf_contraseña = new javax.swing.JTextField();
        cb_pf_membresia = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        sp_pf_spinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_pf_descripcion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lb_pf_foto = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_pf = new javax.swing.JTextArea();
        MENU = new javax.swing.JDialog();
        jb_prem = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        LISTAR = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        J_list = new javax.swing.JList<>();
        PERFIL = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_crear_nombre1 = new javax.swing.JTextField();
        cb_sexo1 = new javax.swing.JComboBox<>();
        tf_crear_usuario1 = new javax.swing.JTextField();
        tf_crear_contraseña1 = new javax.swing.JTextField();
        cb_membresia1 = new javax.swing.JComboBox<>();
        sp_spinner1 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_descripcion1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lb_foto1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tf_int = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        Solicitudes = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        MENSAJE = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        ta_mnsj = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        list_para = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        list_msnj = new javax.swing.JList<>();
        jLabel28 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Modificar = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_crear_nombre2 = new javax.swing.JTextField();
        cb_sexo2 = new javax.swing.JComboBox<>();
        tf_crear_usuario2 = new javax.swing.JTextField();
        tf_crear_contraseña2 = new javax.swing.JTextField();
        cb_membresia2 = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        sp_spinner2 = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ta_descripcion2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lb_foto2 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tf_int1 = new javax.swing.JTextArea();
        jButton17 = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JDialog();
        jScrollPane12 = new javax.swing.JScrollPane();
        list_para1 = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_inicio_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_inicio_contra = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel3.setText("Nombre");

        jLabel4.setText("Edad");

        jLabel5.setText("Sexo");

        jLabel6.setText("Usuario");

        jLabel7.setText("Contraseña");

        jLabel8.setText("Membresia");

        cb_pf_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        cb_pf_membresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        sp_pf_spinner.setModel(new javax.swing.SpinnerNumberModel(18, 18, 40, 1));

        jLabel9.setText("Descripcion");

        ta_pf_descripcion.setColumns(20);
        ta_pf_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_pf_descripcion);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_pf_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_pf_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setText("Seleccionar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel10.setText("Intereses");

        ta_pf.setColumns(20);
        ta_pf.setRows(5);
        jScrollPane2.setViewportView(ta_pf);

        javax.swing.GroupLayout CREAR_USUARIOLayout = new javax.swing.GroupLayout(CREAR_USUARIO.getContentPane());
        CREAR_USUARIO.getContentPane().setLayout(CREAR_USUARIOLayout);
        CREAR_USUARIOLayout.setHorizontalGroup(
            CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CREAR_USUARIOLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CREAR_USUARIOLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(582, 582, 582))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CREAR_USUARIOLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(364, 364, 364))))
            .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(59, 59, 59)
                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_pf_membresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                                .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cb_pf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_pf_nombre)
                                        .addComponent(tf_pf_usuario)
                                        .addComponent(tf_pf_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                                    .addComponent(sp_pf_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(jLabel10))
                                    .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CREAR_USUARIOLayout.setVerticalGroup(
            CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_pf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sp_pf_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_pf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_pf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_pf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cb_pf_membresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CREAR_USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CREAR_USUARIOLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jButton4))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jButton3)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jb_prem.setText("Premium");
        jb_prem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_premMouseClicked(evt);
            }
        });

        jButton6.setText("Usuarios");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Perfil");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Calendario");

        jButton9.setText("Mensajes");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton11.setText("Solicitudes");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MENULayout = new javax.swing.GroupLayout(MENU.getContentPane());
        MENU.getContentPane().setLayout(MENULayout);
        MENULayout.setHorizontalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton6)
                        .addGap(92, 92, 92)
                        .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addGroup(MENULayout.createSequentialGroup()
                                .addComponent(jb_prem)
                                .addGap(89, 89, 89)
                                .addComponent(jButton8))))
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButton9)
                        .addGap(77, 77, 77)
                        .addComponent(jButton11)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        MENULayout.setVerticalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton7)
                .addGap(61, 61, 61)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_prem)
                    .addComponent(jButton8)
                    .addComponent(jButton6))
                .addGap(55, 55, 55)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton11))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        LISTAR.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                LISTARWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                LISTARWindowClosing(evt);
            }
        });

        J_list.setModel(new DefaultListModel());
        J_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J_listMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(J_list);

        javax.swing.GroupLayout LISTARLayout = new javax.swing.GroupLayout(LISTAR.getContentPane());
        LISTAR.getContentPane().setLayout(LISTARLayout);
        LISTARLayout.setHorizontalGroup(
            LISTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LISTARLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        LISTARLayout.setVerticalGroup(
            LISTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LISTARLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabel11.setText("Nombre");

        jLabel12.setText("Edad");

        jLabel13.setText("Sexo");

        jLabel14.setText("Usuario");

        jLabel15.setText("Contraseña");

        jLabel16.setText("Membresia");

        tf_crear_nombre1.setEditable(false);

        cb_sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        tf_crear_usuario1.setEditable(false);

        tf_crear_contraseña1.setEditable(false);

        cb_membresia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        sp_spinner1.setModel(new javax.swing.SpinnerNumberModel(18, 18, 40, 1));

        jLabel17.setText("Descripcion");

        ta_descripcion1.setEditable(false);
        ta_descripcion1.setColumns(20);
        ta_descripcion1.setRows(5);
        jScrollPane3.setViewportView(ta_descripcion1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_foto1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_foto1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton10.setText("Seleccionar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel18.setText("Intereses");

        tf_int.setColumns(20);
        tf_int.setRows(5);
        jScrollPane5.setViewportView(tf_int);

        jButton12.setText("Agregar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setText("Bloquear");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PERFILLayout = new javax.swing.GroupLayout(PERFIL.getContentPane());
        PERFIL.getContentPane().setLayout(PERFILLayout);
        PERFILLayout.setHorizontalGroup(
            PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PERFILLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PERFILLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(76, 76, 76)
                        .addComponent(jButton13)
                        .addGap(31, 31, 31)
                        .addComponent(jButton12)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PERFILLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(364, 364, 364))))
            .addGroup(PERFILLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(59, 59, 59)
                .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_membresia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PERFILLayout.createSequentialGroup()
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_crear_nombre1)
                                .addComponent(tf_crear_usuario1)
                                .addComponent(tf_crear_contraseña1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                            .addComponent(sp_spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PERFILLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel18))
                            .addGroup(PERFILLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PERFILLayout.setVerticalGroup(
            PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PERFILLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PERFILLayout.createSequentialGroup()
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_crear_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(sp_spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cb_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_crear_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PERFILLayout.createSequentialGroup()
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_crear_contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cb_membresia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PERFILLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PERFILLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jButton10))))
                    .addGroup(PERFILLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(PERFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton12)
                            .addComponent(jButton13))))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jList1);

        javax.swing.GroupLayout SolicitudesLayout = new javax.swing.GroupLayout(Solicitudes.getContentPane());
        Solicitudes.getContentPane().setLayout(SolicitudesLayout);
        SolicitudesLayout.setHorizontalGroup(
            SolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolicitudesLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        SolicitudesLayout.setVerticalGroup(
            SolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolicitudesLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        ta_mnsj.setColumns(20);
        ta_mnsj.setRows(5);
        jScrollPane7.setViewportView(ta_mnsj);

        jLabel19.setText("Para: ");

        list_para.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(list_para);

        list_msnj.setModel(new DefaultListModel());
        jScrollPane11.setViewportView(list_msnj);

        jLabel28.setText("nuevo mensaje");

        jButton5.setText("enviar");

        jLabel29.setText("tus mensajes");

        javax.swing.GroupLayout MENSAJELayout = new javax.swing.GroupLayout(MENSAJE.getContentPane());
        MENSAJE.getContentPane().setLayout(MENSAJELayout);
        MENSAJELayout.setHorizontalGroup(
            MENSAJELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENSAJELayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(MENSAJELayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel19)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MENSAJELayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(201, 201, 201))
        );
        MENSAJELayout.setVerticalGroup(
            MENSAJELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENSAJELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MENSAJELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGroup(MENSAJELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MENSAJELayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(MENSAJELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MENSAJELayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENSAJELayout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(MENSAJELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENSAJELayout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENSAJELayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(77, 77, 77))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENSAJELayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(61, 61, 61))))
        );

        jLabel20.setText("Nombre");

        jLabel21.setText("Edad");

        jLabel22.setText("Sexo");

        jLabel23.setText("Usuario");

        jLabel24.setText("Contraseña");

        jLabel25.setText("Membresia");

        cb_sexo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        cb_membresia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jButton14.setText("MODIFICAR");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        sp_spinner2.setModel(new javax.swing.SpinnerNumberModel(18, 18, 40, 1));

        jLabel26.setText("Descripcion");

        ta_descripcion2.setColumns(20);
        ta_descripcion2.setRows(5);
        jScrollPane9.setViewportView(ta_descripcion2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_foto2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_foto2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton15.setText("Seleccionar");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jLabel27.setText("Intereses");

        tf_int1.setColumns(20);
        tf_int1.setRows(5);
        jScrollPane10.setViewportView(tf_int1);

        jButton17.setText("ELIMINAR AMIGO");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar.getContentPane());
        Modificar.getContentPane().setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15)
                        .addGap(76, 76, 76)
                        .addComponent(jButton17)
                        .addGap(391, 391, 391))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(364, 364, 364))))
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(59, 59, 59)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_membresia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ModificarLayout.createSequentialGroup()
                                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cb_sexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_crear_nombre2)
                                        .addComponent(tf_crear_usuario2)
                                        .addComponent(tf_crear_contraseña2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                                    .addComponent(sp_spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ModificarLayout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(jLabel27))
                                    .addGroup(ModificarLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tf_crear_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(sp_spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(cb_sexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_crear_usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(tf_crear_contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(cb_membresia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ModificarLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jButton15))))
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton17)))
                .addGap(64, 64, 64)
                .addComponent(jButton14)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        list_para1.setModel(new DefaultListModel());
        list_para1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_para1MouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(list_para1);

        jLabel30.setText("Seleccione para eliminar");

        javax.swing.GroupLayout ELIMINARLayout = new javax.swing.GroupLayout(ELIMINAR.getContentPane());
        ELIMINAR.getContentPane().setLayout(ELIMINARLayout);
        ELIMINARLayout.setHorizontalGroup(
            ELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELIMINARLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(ELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        ELIMINARLayout.setVerticalGroup(
            ELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELIMINARLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel30)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USUARIO");

        jLabel2.setText("CONTRASEÑA");

        jButton1.setText("INICIAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("CREAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_inicio_user)
                            .addComponent(tf_inicio_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jButton1)))
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_inicio_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jButton2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_inicio_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        //String nombre, int edad, String sexo, String nombre_usuario, String contraseña, String descripcion, Image imagen, String membresia
        String nombre, sexo, nombreusuario, contraseña, descripcion, membresia;
        int edad;
        ArrayList<String> intereses = new ArrayList();
        Image imagen;
        nombre = tf_pf_nombre.getText();
        sexo = (String) cb_pf_sexo.getSelectedItem();
        nombreusuario = tf_pf_usuario.getText();
        contraseña = tf_pf_contraseña.getText();
        descripcion = ta_pf_descripcion.getText();
        membresia = (String) cb_pf_membresia.getSelectedItem();
        edad = (int) sp_pf_spinner.getValue();
        ayuda = ta_pf.getText();
        if (nombre.contains("1") || nombre.contains("2") || nombre.contains("3") || nombre.contains("4") | nombre.contains("5")
                || nombre.contains("6") || nombre.contains("7") || nombre.contains("8") || nombre.contains("9") || nombre.contains("0") || nombre.length() < 3 || contraseña.length() < 8 || descripcion.length() < 5
                || ayuda.length() < 5) {
            JOptionPane.showMessageDialog(this, "esta ingresando datos que no son o la contraseña es menor a 8");
        } else {
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            USUARIO us = new USUARIO(nombre, edad, sexo, nombreusuario, contraseña, descripcion, lb_pf_foto.getIcon(), membresia);
            us.getIntereses().add(intereses);
            Admin_usuarios ap = new Admin_usuarios("./users.lab");
            ap.cargarArchivo();
            ap.setUsuario(us);
            ap.escribirArchivo();
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:

        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("IMAGENES", "PGN", "JPG", "JPEG", "GIF");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            this.lb_pf_foto.setIcon(new ImageIcon(img));
        }

    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        CREAR_USUARIO.setModal(true);
        CREAR_USUARIO.pack();
        CREAR_USUARIO.setLocationRelativeTo(this);
        CREAR_USUARIO.setVisible(true);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        Admin_usuarios ad_u = new Admin_usuarios("./users.lab");
        ad_u.cargarArchivo();
        String user, pass, memb;
        memb = (String) cb_pf_membresia.getSelectedItem();
        user = tf_inicio_user.getText();
        pass = tf_inicio_contra.getText();
        try {
            for (USUARIO i : ad_u.getUsuarios()) {
                if (i.getNombre_usuario().equals(user) && i.getContraseña().equals(pass)) {
                    usuario_yo = i;
                    index = ad_u.getUsuarios().indexOf(i);
                    ad_u.getUsuarios().add(usuario_yo);
                    if (memb.equals("Si")) {
                        MENU.setModal(true);
                        MENU.pack();
                        MENU.setLocationRelativeTo(this);
                        MENU.setVisible(true);
                        jb_prem.setVisible(true);
                    } else {
                        MENU.setModal(true);
                        MENU.pack();
                        MENU.setLocationRelativeTo(this);
                        MENU.setVisible(true);
                        jb_prem.setVisible(false);
                    }
                } else {
                }
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        Admin_usuarios ap = new Admin_usuarios("./users.lab");
        ap.cargarArchivo();
        DefaultListModel m = (DefaultListModel) J_list.getModel();
        for (USUARIO i : ap.getUsuarios()) {
            m.addElement(i.toString());
        }
        for (Object i : ap.getUsuarios().get(index).getBloqueados()) {
            m.removeElement(i);
        }
        J_list.setModel(m);
        LISTAR.setModal(true);
        LISTAR.pack();
        LISTAR.setLocationRelativeTo(this);
        LISTAR.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void LISTARWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LISTARWindowClosed
        // TODO add your handling code here:
        DefaultListModel m = (DefaultListModel) J_list.getModel();
        m.removeAllElements();
        J_list.setModel(m);
    }//GEN-LAST:event_LISTARWindowClosed

    private void LISTARWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LISTARWindowClosing
        // TODO add your handling code here:
        DefaultListModel m = (DefaultListModel) J_list.getModel();
        m.removeAllElements();
        J_list.setModel(m);
    }//GEN-LAST:event_LISTARWindowClosing

    private void J_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_listMouseClicked
        // TODO add your handling code here:
        Admin_usuarios ap = new Admin_usuarios("./users.lab");
        ap.cargarArchivo();
        J_list.getSelectedIndex();
        usuario_el = ap.getUsuarios().get(J_list.getSelectedIndex());
        ap.getUsuarios().get(J_list.getSelectedIndex());
        tf_crear_nombre1.setText(ap.getUsuarios().get(J_list.getSelectedIndex()).getNombre());
        sp_spinner1.setValue(ap.getUsuarios().get(J_list.getSelectedIndex()).getEdad());
        cb_sexo1.setSelectedItem(ap.getUsuarios().get(J_list.getSelectedIndex()).getEdad());
        tf_crear_usuario1.setText(ap.getUsuarios().get(J_list.getSelectedIndex()).getNombre_usuario());
        tf_crear_contraseña1.setText(ap.getUsuarios().get(J_list.getSelectedIndex()).getContraseña());
        cb_sexo1.setSelectedItem(ap.getUsuarios().get(J_list.getSelectedIndex()).getContraseña());
        ta_descripcion1.setText(ap.getUsuarios().get(J_list.getSelectedIndex()).getDescripcion());
        lb_foto1.setIcon(ap.getUsuarios().get(J_list.getSelectedIndex()).getImagen());
        tf_int.setText(ta_pf.getText());
        ap.escribirArchivo();
        PERFIL.setModal(true);
        PERFIL.pack();
        PERFIL.setLocationRelativeTo(this);
        PERFIL.setVisible(true);
    }//GEN-LAST:event_J_listMouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        Admin_usuarios ap = new Admin_usuarios("./users.lab");
        ap.cargarArchivo();
        DefaultListModel m = (DefaultListModel) J_list.getModel();
        ap.getUsuarios().get(index).getBloqueados().add(m.get(J_list.getSelectedIndex()));
        for (Object i : ap.getUsuarios().get(index).getBloqueados()) {
            m.removeElement(i);
        }
        J_list.setModel(m);
        ap.escribirArchivo();
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        Admin_usuarios ap = new Admin_usuarios("./users.lab");
        ap.cargarArchivo();
        DefaultListModel m = (DefaultListModel) jList1.getModel();

        ap.getUsuarios().get(J_list.getSelectedIndex()).getSolicitudes().add(usuario_yo);
        m.removeAllElements();
        for (Object i : ap.getUsuarios().get(J_list.getSelectedIndex()).getSolicitudes()) {
            m.addElement(i);
        }

        jList1.setModel(m);
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "solicitud enviada");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        Solicitudes.setModal(true);
        Solicitudes.pack();
        Solicitudes.setLocationRelativeTo(this);
        Solicitudes.setVisible(true);

    }//GEN-LAST:event_jButton11MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        Admin_usuarios ap = new Admin_usuarios("./users.lab");
        USUARIO su;
        ap.cargarArchivo();
        DefaultListModel m = (DefaultListModel) jList1.getModel();
        int response = JOptionPane.showConfirmDialog(this, "Aceptar?", "confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
            int bn = jList1.getSelectedIndex();
            ap.getUsuarios().get(index).getAmigos().add(m.get(bn));
            if (jList1.getSelectedIndex() >= 0) {

                m.remove(jList1.getSelectedIndex());
                jList1.setModel(m);
            }

        } else {
            if (jList1.getSelectedIndex() >= 0) {

                m.remove(jList1.getSelectedIndex());
                jList1.setModel(m);
            }
        }
        ap.escribirArchivo();
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        Admin_usuarios ap = new Admin_usuarios("./users.lab");
        ap.cargarArchivo();
        DefaultListModel m = (DefaultListModel) list_para.getModel();
        m.removeAllElements();
        for (Object i : ap.getUsuarios().get(index).getAmigos()) {
            m.addElement(i);

        }
        list_para.setModel(m);
        ap.escribirArchivo();
        MENSAJE.setModal(true);
        MENSAJE.pack();
        MENSAJE.setLocationRelativeTo(this);
        MENSAJE.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        Modificar.setModal(true);
        Modificar.pack();
        Modificar.setLocationRelativeTo(this);
        Modificar.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        Admin_usuarios ap = new Admin_usuarios("./users.lab");
        ap.cargarArchivo();
        if (tf_crear_nombre2.getText().contains("1") || tf_crear_nombre2.getText().contains("2") || tf_crear_nombre2.getText().contains("3") || tf_crear_nombre2.getText().contains("4") | tf_crear_nombre2.getText().contains("5")
                || tf_crear_nombre2.getText().contains("6") || tf_crear_nombre2.getText().contains("7") || tf_crear_nombre2.getText().contains("8") || tf_crear_nombre2.getText().contains("9") || tf_crear_nombre2.getText().contains("0") || tf_crear_nombre2.getText().length() < 3
                || tf_crear_contraseña2.getText().length() < 8 || ta_descripcion2.getText().length() < 5
                || ayuda.length() < 5) {
            JOptionPane.showMessageDialog(this, "esta ingresando datos que no son o la contraseña es menor a 8 caracteres");
        }
        ap.getUsuarios().get(index).setNombre(tf_crear_nombre2.getText());
        ap.getUsuarios().get(index).setEdad(Integer.parseInt((String) sp_spinner2.getValue()));
        ap.getUsuarios().get(index).setNombre_usuario(tf_crear_usuario2.getText());
        ap.getUsuarios().get(index).setContraseña(tf_crear_contraseña2.getText());
        ap.getUsuarios().get(index).setMembresia((String) cb_membresia2.getSelectedItem());
        ap.getUsuarios().get(index).setImagen(lb_foto2.getIcon());
        ap.getUsuarios().get(index).setDescripcion(ta_descripcion2.getText());
        ayuda = tf_int1.getText();

    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        // TODO add your handling code here:
        try {
            Admin_usuarios ap = new Admin_usuarios("./users.lab");
            ap.cargarArchivo();
            DefaultListModel m = (DefaultListModel) list_para1.getModel();
            m.removeAllElements();
            for (Object i : ap.getUsuarios().get(index).getAmigos()) {
                m.addElement(i);
                System.out.println(i);
            }
            

            list_para1.setModel(m);
            ap.escribirArchivo();

        } catch (Exception e) {
        }
        ELIMINAR.setModal(true);
        ELIMINAR.pack();
        ELIMINAR.setLocationRelativeTo(this);
        ELIMINAR.setVisible(true);
    }//GEN-LAST:event_jButton17MouseClicked

    private void list_para1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_para1MouseClicked
        // TODO add your handling code here:
        try {
        Admin_usuarios ap = new Admin_usuarios("./users.lab");
        ap.cargarArchivo();

        DefaultListModel m = (DefaultListModel) list_para1.getModel();
        int response = JOptionPane.showConfirmDialog(this, "Aceptar?", "confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
              if (list_para1.getSelectedIndex() >= 0) {
            m.remove(list_para1.getSelectedIndex());
            ap.getUsuarios().get(index).getAmigos().remove(m.get(list_para1.getSelectedIndex()));

        System.out.println(ap.getUsuarios().get(index).getAmigos());
              
            }
            
        }
            list_para1.setModel(m);
            ap.escribirArchivo();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_list_para1MouseClicked

    private void jb_premMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_premMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jb_premMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CREAR_USUARIO;
    private javax.swing.JDialog ELIMINAR;
    private javax.swing.JList<String> J_list;
    private javax.swing.JDialog LISTAR;
    private javax.swing.JDialog MENSAJE;
    private javax.swing.JDialog MENU;
    private javax.swing.JDialog Modificar;
    private javax.swing.JDialog PERFIL;
    private javax.swing.JDialog Solicitudes;
    private javax.swing.JComboBox<String> cb_membresia1;
    private javax.swing.JComboBox<String> cb_membresia2;
    private javax.swing.JComboBox<String> cb_pf_membresia;
    private javax.swing.JComboBox<String> cb_pf_sexo;
    private javax.swing.JComboBox<String> cb_sexo1;
    private javax.swing.JComboBox<String> cb_sexo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jb_prem;
    private javax.swing.JLabel lb_foto1;
    private javax.swing.JLabel lb_foto2;
    private javax.swing.JLabel lb_pf_foto;
    private javax.swing.JList<String> list_msnj;
    private javax.swing.JList<String> list_para;
    private javax.swing.JList<String> list_para1;
    private javax.swing.JSpinner sp_pf_spinner;
    private javax.swing.JSpinner sp_spinner1;
    private javax.swing.JSpinner sp_spinner2;
    private javax.swing.JTextArea ta_descripcion1;
    private javax.swing.JTextArea ta_descripcion2;
    private javax.swing.JTextArea ta_mnsj;
    private javax.swing.JTextArea ta_pf;
    private javax.swing.JTextArea ta_pf_descripcion;
    private javax.swing.JTextField tf_crear_contraseña1;
    private javax.swing.JTextField tf_crear_contraseña2;
    private javax.swing.JTextField tf_crear_nombre1;
    private javax.swing.JTextField tf_crear_nombre2;
    private javax.swing.JTextField tf_crear_usuario1;
    private javax.swing.JTextField tf_crear_usuario2;
    private javax.swing.JPasswordField tf_inicio_contra;
    private javax.swing.JTextField tf_inicio_user;
    private javax.swing.JTextArea tf_int;
    private javax.swing.JTextArea tf_int1;
    private javax.swing.JTextField tf_pf_contraseña;
    private javax.swing.JTextField tf_pf_nombre;
    private javax.swing.JTextField tf_pf_usuario;
    // End of variables declaration//GEN-END:variables
USUARIO usuario_el;
    USUARIO usuario_yo;
    ArrayList<USUARIO> ayuda_users = new ArrayList();
    String ayuda;
    int index = 0;
}
